const con=[
    {
        info1:"Dog",
        info2:"Walking",
        img:"download.jpeg"
    },
    {
        info1:"Dog",
        info2:"Walking",
        img:"download.jpeg"
    },
    {
        info1:"Dog",
        info2:"Walking",
        img:"download.jpeg"
    },
    {
        info1:"Dog",
        info2:"Walking",
        img:"download.jpeg"
    },
    {
        info1:"Dog",
        info2:"Walking",
        img:"download.jpeg"
    },
    {
        info1:"Dog",
        info2:"Walking",
        img:"download.jpeg"
    },
    {
        info1:"Dog",
        info2:"Walking",
        img:"download.jpeg"
    },
    {
        info1:"Dog",
        info2:"Walking",
        img:"download.jpeg"
    },
]
export default con;